version: "3.4"
services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    userns_mode: "host"
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
      - ./log/nginx:/var/log/nginx
  php:
    build:
      context: ./docker/php
    userns_mode: "host"
    container_name: "wp_php"
    user: "1000:1000"
    ports:
      - "9000"
    expose:
      - 9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - mysql
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-php.ini
      - ./app:/var/www/html

  mysql:
    image: mysql:latest
    userns_mode: "host"
    container_name: "wp_mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wp_root_password
      - MYSQL_DATABASE=wp_db
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
      - TERM=meh